### ISSUE TITLE
Bundle affwp-addon-tools and implement requirement checks

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/affiliatewp-sign-up-bonus#17]
In order to facilitate enforcing [minimum dependency requirements](https://docs.affiliatewp.com/article/2361-minimum-requirements-roadmaps) going forward, we need to bundle the affwp-addon-tools package via composer and refactor the plugin bootstrap to extend the requirements class.

**Comment by dbeja** [comment]
PR: #18

**Comment by dbeja** [comment]
Merged #18 against `release/1.2`.
